powerpc/fadump: Fix compile error due to missing semicolon
The commit "powerpc/fadump: trivial fix of spelling mistake, clean up
message" removed a semicolon causing the following compile failure:

arch/powerpc/kernel/fadump.c: In function ‘fadump_invalidate_dump’:
arch/powerpc/kernel/fadump.c:1014:2: error: expected ‘;’ before ‘}’ token
  }
  ^

Reported-by: Huy Nguyen <huyn@mellanox.com>
Signed-off-by: Ian Munsie <imunsie@au1.ibm.com>